# Generated by Django 6.1 on 2026-08-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_subject_required_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['day', 'period']},
        ),
        migrations.AlterField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='scheduler.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduler.batch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduler.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduler.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='scheduler.department'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.batch'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.room'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.subject'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.teacher'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('department', 'year', 'section'), name='unique_batch_per_dept_year_section'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('day', 'period', 'room'), name='unique_room_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('day', 'period', 'teacher'), name='unique_teacher_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('day', 'period', 'batch'), name='unique_batch_slot'),
        ),
    ]
